import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip"
import localFont from "next/font/local"

const jbmono = localFont({
  src: [
    {
      path: '../../public/fonts/JetBrainsMono-Regular.woff2',
      weight: "400",
      style: "normal"
    }
  ],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Сроки 2.0",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={
        `${jbmono.className} h-full`
      }
      suppressHydrationWarning
    >
      <body className="min-h-0 h-full">

        <ThemeProvider attribute={"class"} defaultTheme="dark" disableTransitionOnChange>
          <div className="min-h-0 h-full">
            <TooltipProvider>
              {children}
            </TooltipProvider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
