import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip"
import { ModeToggle } from "@/components/custom/themeModeToggler";

const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-mono' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-mono", jetbrainsMono.variable)}
      suppressHydrationWarning
    >
      <body className="min-h-0 h-full">

        <ThemeProvider attribute={"class"} defaultTheme="dark" enableSystem disableTransitionOnChange>
          <div className="min-h-0 h-full">
            <TooltipProvider>
              {children}
            </TooltipProvider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
